pipeline {
    agent any
	stages{

        stage('Install Docker') {
            steps {
                build job: 'Installing-docker'
            }
        }

        stage('Deploy PHP App') {
            steps {
                build job: 'Building and runnig docker'
            }
        }
	}
}
