pipeline {
    agent any
    environment{
	PATH = "/usr/bin:${env.PATH}"
	}
	stages{
        stage('Run Ansible Playbook')
	{
	   steps{
            sshagent(credentials: ['ansible-key']) {
	     
                sh 'ansible-playbook -i hosts install_docker.yaml' --ssh-extra-args = '-o StrictHostKeyChecking=no'
            }
        }
    }
}
}
