pipeline {
    agent any
    environment{
	PATH = "/usr/bin:${env.PATH}
	}
	stages{
        stage('Run Ansible Playbook') {
            steps {
                sh 'ansible-playbook -i inventory ansible-playbooks/install_docker.yaml'
            }
        }
    }
}
