pipeline {
    agent any
    environment {
    PATH = "/usr/local/bin:/usr/bin:${env.PATH}"
	}
	stages{
        stage('Run Ansible Playbook') {
            steps {
                sh 'ansible-playbook -i inventory install_docker.yaml'
            }
        }
    }
}
