pipeline {
    agent any
    environment{
	PATH = "/usr/bin:${env.PATH}"
	HOSTS = '/home/ec2-user/edureka/ansible/hosts'
	}
	stages{
        stage('Run Ansible Playbook')
	{
	   steps{
            sshagent(credentials: ['ansible-key']) {
	     
                sh 'ansible -i $HOSTS testserver -m ping'
            }
        }
    }
}
}
